In [2]:
import numpy as np
import time


## What is this array declaration doing

In [3]:
myArray = np.array([[1,2], [3,4]])
print(myArray)

[[1 2]
 [3 4]]


## Numpy provides many fast options for array manipulation

In [4]:

num = 1000
a = np.random.rand(num,num)
now = time.time()
b = a * a
then = time.time()

print('time taken:', then-now, 'seconds')


time taken: 0.0050318241119384766 seconds


In [5]:
c = np.zeros([num,num])

now = time.time()
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        c[i,j] = a[i,j]*a[i,j]
then = time.time()
print('time taken:', then-now, 'seconds')


time taken: 0.4299967288970947 seconds


In [6]:
print('observe that arrays b and c are the same')
print(b-c)

observe that arrays b and c are the same
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


## Broadcasting arrays

In [7]:
A = np.array(range(8*5*7))
A = np.reshape(A, [8, 5, 7])
B = np.array([1,2,3,4,5])
B = np.reshape(B, [5,1])
print('shape of A:',A.shape)
print('shape of B:', B.shape)

shape of A: (8, 5, 7)
shape of B: (5, 1)


In [8]:
index = 0
print('First slice of A')
print(A[index])
print('')
print('Vector B')
print(B)

First slice of A
[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]]

Vector B
[[1]
 [2]
 [3]
 [4]
 [5]]


In [8]:
C = A - B
print('First Slice of C, where C = A - B')
print(C[index])

First Slice of C, where C = A - B
[[-1  0  1  2  3  4  5]
 [ 5  6  7  8  9 10 11]
 [11 12 13 14 15 16 17]
 [17 18 19 20 21 22 23]
 [23 24 25 26 27 28 29]]


## Can you see how the array subtraction occured

## More about arrays

In [25]:
print('Integer array')
myArray = np.array([[1,700], [3,4]])
print(myArray)

print('Float array')
myArray = myArray.astype('float')
print(myArray)


print('uint8 array')
myArray = np.array([[1,700], [256,255]], 'uint8')
print(myArray)


print('Float array')
myArray = np.array([[1,2], [3,4]], dtype='float')
print(myArray)

print('Float array')
myArray = np.array([[1.0,2], [3,4]], dtype='float')
print(myArray)

Integer array
[[  1 700]
 [  3   4]]
Float array
[[  1. 700.]
 [  3.   4.]]
uint8 array
[[  1 188]
 [  0 255]]
Float array
[[1. 2.]
 [3. 4.]]
Float array
[[1. 2.]
 [3. 4.]]



## Numpy provides many fast, array  manipulation functions.
## These functions allow us to control the size of output arrays. This is important for broadcasting


In [8]:
data = np.random.random([1000,100])
print('shape of data matrix')
print(data.shape)


shape of data matrix
(1000, 100)


In [10]:
m = np.min(data, axis=1)
print('take the minimum value in each row')
print(m.shape)


take the minimum value in each row
(1000,)


In [11]:
print('this does not work')
data-m


this does not work


ValueError: operands could not be broadcast together with shapes (1000,100) (1000,) 

In [12]:
print('However, this can work')
m = np.min(data, axis=1, keepdims=True)
data - m

However, this can work


array([[0.40176721, 0.56238451, 0.2257611 , ..., 0.41731349, 0.37000143,
        0.57259619],
       [0.5766069 , 0.50246475, 0.07622123, ..., 0.92864077, 0.28942509,
        0.48292137],
       [0.23366729, 0.09847839, 0.88483767, ..., 0.05734237, 0.09917095,
        0.09440202],
       ...,
       [0.68979375, 0.65345273, 0.43356701, ..., 0.21710438, 0.57459514,
        0.49434184],
       [0.51005637, 0.70156168, 0.32494137, ..., 0.32019552, 0.65872564,
        0.79056542],
       [0.69623255, 0.45648305, 0.48302211, ..., 0.45292422, 0.05547434,
        0.20156482]])

In [13]:
m.shape

(1000, 1)