## Python's heavy dependence on libararies mean there are many duplicate functions with differing prperties

In [1]:
import numpy as np

matrix = np.matrix([[0,1,2], [3,4,5], [6,7,8]])
array =  np.array([[0,1,2], [3,4,5], [6,7,8]])
list_ = [0, 7, 8, 9]
print('Matrix multiplication')
print(matrix*matrix)
print('Array multiplication')
print(array*array)
print('Array and matrix')
print(array*matrix)

Matrix multiplication
[[ 15  18  21]
 [ 42  54  66]
 [ 69  90 111]]
Array multiplication
[[ 0  1  4]
 [ 9 16 25]
 [36 49 64]]
Array and matrix
[[ 15  18  21]
 [ 42  54  66]
 [ 69  90 111]]


## There are two versions of max

In [2]:
print('with np max:', np.max(array))
print('with np max:', np.max(array, axis=1))
print(max(list_))

with np max: 8
with np max: [2 5 8]
9


In [3]:
print('This does not work')
max(array)

This does not work


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [15]:
import random
print('numpy random:', np.random.random(10))
print('python random:', random.random())

numpy random: [0.09197991 0.26898255 0.97208746 0.84393425 0.2988826  0.61216913
 0.42619621 0.45929392 0.38960505 0.37524448]
python random: 0.7937713323745155


In [19]:
print('This does not work:')
random.random(10)

This does not work:


TypeError: random() takes no arguments (1 given)